### ISSUE TITLE
Initial momentum is too high

### ISSUE THREAD

**Issue by sbird** [sbird/npfp#2]
Without setting the momentum to zero, the particles quickly head to infinity until the floating point overflows.

**Comment by sbird** [comment]
https://articles.adsabs.harvard.edu/pdf/1974A%26A....37..183A

**Comment by Faezehmanesh** [comment]
![IMG_3637](https://github.com/sbird/npfp/assets/108970900/071b0f7c-ddaf-4e41-9e30-d01656aaa541)
problem SOLVED!

**Comment by sbird** [comment]
Great!

**Comment by Faezehmanesh** [comment]
let's go for the next issues.
